### PR TITLE
Always close SQLiteStatements

### PR DESCRIPTION
**Pull request by maxpowa**
Re-application of #15

### CODE REVIEW

**Comment by brodybits** [comment]
Thanks, but I am not ready to re-include the fix right now. I want to first apply it to the cipher-src branch then merge it in.

**Comment by brodybits** [comment]
I need to sort some other issues with the source before dealing with this one. It will be 2-3 weeks.

**Comment by maxpowa** [comment]
That's cool, I'll just use my fork for now. Thanks

**Comment by brodybits** [comment]
On Fri, Jan 29, 2016 at 8:37 PM, Max Gurela <notifications@github.com>
wrote:

> That's cool, I'll just use my fork for now. Thanks
>

Perfect, thanks for your understanding. Thanks again for pointing it out.

**Pull request closed without merging**
