### PR TITLE
Fix Windows build fails due to incorrect dep references

### LINKED ISSUE #32: Windows build fails due to incorrect dep references
```
λ cordova --version
6.2.0
λ cordova platforms
  windows 4.3.2
```
```
C:\temp\sqlCipher
λ cordova build windows --archs=x86
Building project: C:\temp\sqlCipher\platforms\windows\CordovaApp.Windows.jsproj
        Configuration : debug
        Platform      : x86
  pch.cpp
  Constants.cpp
  Database.cpp
  Statement.cpp
c:\temp\sqlcipher\plugins\cordova-sqlcipher-adapter\src\windows\sqlite3-win-rt\sqlite3\database.cpp(57): warning C4244: 'return' : conversion from 'sqlite3_int64' to 'int', possible loss of data [C:\temp\sqlCip her\plugins\cordova-sqlcipher-adapter\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.Windows\SQLite3.Windows.vcxproj]
  sqlite3.c
  cbc_encrypt.c
  cbc_decrypt.c
  cbc_start.c
  cbc_done.c
  crypt_find_cipher.c
  crypt_find_hash.c
  crypt_register_hash.c
c1 : fatal error C1083: Cannot open source file: 'C:\temp\sqlCipher\plugins\cordova-sqlcipher-adapter\src\external\common\sqlite3.c': No such file or directory [C:\temp\sqlCipher\plugins\cordova-sqlcipher-adapt er\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.Windows\SQLite3.Windows.vcxproj]
c1 : fatal error C1083: Cannot open source file: 'C:\temp\sqlCipher\plugins\cordova-sqlcipher-adapter\src\external\libTomCrypt\crypt_find_hash.c': No such file or directory [C:\temp\sqlCipher\plugins\cordova-sq lcipher-adapter\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.Windows\SQLite3.Windows.vcxproj]
c1 : fatal error C1083: Cannot open source file: 'C:\temp\sqlCipher\plugins\cordova-sqlcipher-adapter\src\external\libTomCrypt\crypt_find_cipher.c': No such file or directory [C:\temp\sqlCipher\plugins\cordova- sqlcipher-adapter\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.Windows\SQLite3.Windows.vcxproj]
c1 : fatal error C1083: Cannot open source file: 'C:\temp\sqlCipher\plugins\cordova-sqlcipher-adapter\src\external\libTomCrypt\crypt_register_hash.c': No such file or directory [C:\temp\sqlCipher\plugins\cordov a-sqlcipher-adapter\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.Windows\SQLite3.Windows.vcxproj]
c1 : fatal error C1083: Cannot open source file: 'C:\temp\sqlCipher\plugins\cordova-sqlcipher-adapter\src\external\libTomCrypt\cbc_encrypt.c': No such file or directory [C:\temp\sqlCipher\plugins\cordova-sqlcip her-adapter\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.Windows\SQLite3.Windows.vcxproj]
c1 : fatal error C1083: Cannot open source file: 'C:\temp\sqlCipher\plugins\cordova-sqlcipher-adapter\src\external\libTomCrypt\cbc_done.c': No such file or directory [C:\temp\sqlCipher\plugins\cordova-sqlcipher -adapter\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.Windows\SQLite3.Windows.vcxproj]
c1 : fatal error C1083: Cannot open source file: 'C:\temp\sqlCipher\plugins\cordova-sqlcipher-adapter\src\external\libTomCrypt\cbc_start.c': No such file or directory [C:\temp\sqlCipher\plugins\cordova-sqlciphe r-adapter\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.Windows\SQLite3.Windows.vcxproj]
c1 : fatal error C1083: Cannot open source file: 'C:\temp\sqlCipher\plugins\cordova-sqlcipher-adapter\src\external\libTomCrypt\cbc_decrypt.c': No such file or directory [C:\temp\sqlCipher\plugins\cordova-sqlcip her-adapter\src\windows\SQLite3-Win-RT\SQLite3\SQLite3.Windows\SQLite3.Windows.vcxproj]
...
Error: C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe: Command failed with exit code 1
```

_libTomCrypt_ is stored in `src\windows\` but the plugin expects it to be in `src\external\` folder.

### PR DESCRIPTION
**Pull request by sgrebnov**
This fixes #32.

### CODE REVIEW

**Comment by brodybits** [comment]
Thanks! Will be included within the next hour or so.

**Comment by brodybits** [comment]
Thanks! I will include this within the next hour or so.

**Comment by sgrebnov** [comment]
Thank you :+1: 
I see there is Travis build failure, as per log this seems to be unrelated, is it something expected?

**Comment by brodybits** [comment]
Your change is now incorporated in the default branch. I cherry-picked it since there was another change that I forgot to push before. Please test the default branch and confirm that it is working for you on Windows.

You can ignore the Travis build failure. Unfortunately Travis CI seems to be a bit flakey, especially at certain times of the day. I think Travis CI works best before noon CET.

**Comment by brodybits** [comment]
And it even passed Travis CI after I cherry-picked your fix!

**Pull request closed without merging**
